Repository Wedemy/eggeum-android, pull requests merged in 2023-12, with the labels that each got.

#162 Netword Module 설정 변경
  data/src/main/kotlin/us/wedemy/eggeum/android/data/di/NetworkModule.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/di/ServiceModule.kt
Labels: bug, refactoring

#170 고객 지원 문의 하기 기능 구현
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/report/ReportDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/report/ReportDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/ReportRepositoryImpl.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/ReportRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/ReportUseCase.kt
  main/src/main/AndroidManifest.xml
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/InquiryFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/MyAccountFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/ReportCompleteFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/ReportFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/InquiryViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/ReportViewModel.kt
  main/src/main/res/layout/fragment_report.xml
  main/src/main/res/layout/fragment_report_complete.xml
  main/src/main/res/navigation/nav_main.xml
  main/src/main/res/values/strings.xml
Labels: enhancement, design

#171 네트워크 에러 화면 구성
  design-resource/src/main/res/drawable/ic_network_error_100.xml
  main/src/main/AndroidManifest.xml
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/NetworkErrorActivity.kt
  main/src/main/res/layout/activity_network_error.xml
  main/src/main/res/values/strings.xml
Labels: design

#175 맵 마커와 카페 상세 정보 바텀 시트 연동
  app/src/main/AndroidManifest.xml
  common/build.gradle.kts
  common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseBottomSheetFragment.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/Image.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/Info.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/Menu.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/UpsertPlaceRequest.kt
  design-resource/src/main/res/drawable/ic_bottom_sheet_handle.xml
  design-resource/src/main/res/drawable/ic_map_marker_40.xml
  design-resource/src/main/res/drawable/ic_outlet_outlined_24.xml
  design-resource/src/main/res/drawable/ic_rest_room_outlined_24.xml
  design-resource/src/main/res/values/fonts.xml
  design-resource/src/main/res/values/styles.xml
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/place/PlaceEntity.kt
  gradle/libs.versions.toml
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/FileMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/PlaceMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/UserMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/CafeDetailModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/ImageModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/InfoModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/MenuModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/ProductModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MainActivity.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeImageAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeMenuAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeImageViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeMenuViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeDetailFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeImageFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeInfoFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeMenuFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchCafeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/CafeDetailViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchViewModel.kt
  main/src/main/res/layout/fragment_cafe_detail.xml
  main/src/main/res/layout/fragment_cafe_info.xml
  main/src/main/res/layout/fragment_cafe_menu.xml
  main/src/main/res/layout/item_cafe_image.xml
  main/src/main/res/navigation/nav_main.xml
  main/src/main/res/values/strings.xml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/adapter/viewholder/CafeMenuViewHolder.kt
  update-cafe/src/main/res/layout/item_update_cafe_menu.xml
  update-cafe/src/main/res/menu/edit_menu.xml
Labels: enhancement, design

#180 최근 검색어, 카페 검색 환경 구축
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  data/build.gradle.kts
  data/src/main/kotlin/us/wedemy/eggeum/android/data/database/OrmConverter.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/database/PlaceSearchDao.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/database/PlaceSearchDatabase.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/local/PlaceLocalDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/local/PlaceLocalDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/di/DataSourceModule.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/di/DatabaseModule.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/mapper/PlaceMapper.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/PlaceResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/PlaceRepositoryImpl.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/PlaceRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/PlaceUseCase.kt
  gradle/libs.versions.toml
  main/build.gradle.kts
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NewCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/SearchCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NewCafeViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/SearchCafeViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchCafeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchCafeViewModel.kt
  main/src/main/res/layout/fragment_search_cafe.xml
Labels: enhancement

#181 카페 검색 기능 구현
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/paging/PlacePagingSource.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/PlaceUseCase.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NewCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/SearchCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/listener/SearchCafeClickListener.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NewCafeViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/SearchCafeViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchCafeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchCafeViewModel.kt
Labels: enhancement

#183 정보수정제안, 피드백 일부 반영 (전체 X)
  gradle/libs.versions.toml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/UpdateMenuCompleteFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/ProposeCafeInfoViewModel.kt
Labels: refactoring

#184 카페 검색 검색어 여부에 따른 분기 처리 구현
  common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseRecyclerViewAdapter.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/local/PlaceLocalDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/local/PlaceLocalDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/PlaceRepositoryImpl.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/PlaceRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/PlaceUseCase.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NewCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/SearchCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/listener/SearchCafeClickListener.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NewCafeViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/SearchCafeViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchCafeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchCafeViewModel.kt
Labels: enhancement, refactoring

#187 메인 화면 네비게이션 로직 개편
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeDetailFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeImageFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/MapFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchCafeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/CafeDetailViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/MapViewModel.kt
  main/src/main/res/layout/bottom_sheet_cafe_detail.xml
  main/src/main/res/layout/fragment_cafe_image.xml
  main/src/main/res/layout/fragment_cafe_info.xml
  main/src/main/res/layout/fragment_cafe_menu.xml
  main/src/main/res/layout/fragment_map.xml
  main/src/main/res/layout/item_cafe_image.xml
  main/src/main/res/layout/item_cafe_image_detail.xml
  main/src/main/res/navigation/nav_main.xml
Labels: enhancement, design, refactoring
