Repository Wedemy/eggeum-android, pull requests merged in 2023-07, with the labels that each got.

#45 온보딩, 카페 등록 화면 리팩토링
  common/src/main/kotlin/us/wedemy/eggeum/common/util/EditTextState.kt
  common/src/main/kotlin/us/wedemy/eggeum/common/util/TextInputError.kt
  design-resource/src/main/res/drawable/selector_box_stroke_color_gray_200.xml
  design-resource/src/main/res/drawable/selector_box_stroke_color_gray_500.xml
  onboard/build.gradle.kts
  onboard/src/main/AndroidManifest.xml
  onboard/src/main/kotlin/us/wedemy/eggeum/onboard/ui/OnboardActivity.kt
  onboard/src/main/kotlin/us/wedemy/eggeum/onboard/ui/RegisterAccountFragment.kt
  onboard/src/main/kotlin/us/wedemy/eggeum/onboard/ui/RegisterNicknameFragment.kt
  onboard/src/main/kotlin/us/wedemy/eggeum/onboard/viewmodel/OnboardViewModelFactory.kt
  onboard/src/main/kotlin/us/wedemy/eggeum/onboard/viewmodel/RegisterAccountViewModel.kt
  onboard/src/main/kotlin/us/wedemy/eggeum/onboard/viewmodel/RegisterNicknameViewModel.kt
  onboard/src/main/res/layout/activity_onboard.xml
  onboard/src/main/res/layout/fragment_register_account.xml
  onboard/src/main/res/layout/fragment_register_nickname.xml
  onboard/src/main/res/layout/fragment_service_terms.xml
  onboard/src/main/res/navigation/nav_onboard.xml
  onboard/src/main/res/values/strings.xml
  onboard/src/main/res/values/themes.xml
  register-cafe/build.gradle.kts
  register-cafe/src/main/AndroidManifest.xml
  register-cafe/src/main/kotlin/us/wedemy/eggeum/registercafe/ui/RegisterCafeActivity.kt
  register-cafe/src/main/kotlin/us/wedemy/eggeum/registercafe/ui/RegisterCafeFragment.kt
  register-cafe/src/main/kotlin/us/wedemy/eggeum/registercafe/viewmodel/RegisterCafeViewModel.kt
  register-cafe/src/main/kotlin/us/wedemy/eggeum/registercafe/viewmodel/RegisterCafeViewModelFactory.kt
  register-cafe/src/main/res/layout/activity_register_cafe.xml
  register-cafe/src/main/res/layout/fragment_register_cafe.xml
  register-cafe/src/main/res/navigation/nav_register_cafe.xml
  register-cafe/src/main/res/values/themes.xml
  setting/src/main/AndroidManifest.xml
  setting/src/main/kotlin/us/wedemy/eggeum/setting/ui/EditMyInfoFragment.kt
  setting/src/main/kotlin/us/wedemy/eggeum/setting/ui/SettingActivity.kt
  setting/src/main/kotlin/us/wedemy/eggeum/setting/viewmodel/EditMyInfoViewModel.kt
  setting/src/main/res/layout/activity_setting.xml
  setting/src/main/res/layout/fragment_edit_my_info.xml
  setting/src/main/res/values/strings.xml
Labels: enhancement

#51 Notice API 추가 및 hilt convention-plugin 등록
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  build-logic/src/main/kotlin/plugins.kt
  data/build.gradle.kts
  data/src/main/kotlin/us/wedemy/eggeum/android/data/client/HttpClient.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/client/moshi.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/mapper/NoticeMapper.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/notice/NoticeBodyResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/notice/NoticeListResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/NoticeRepositoryProvider.kt
  data/src/test/kotlin/us/wedemy/eggeum/android/data/NoticeTest.kt
  domain/CODEOWNERS
  domain/build.gradle.kts
  domain/src/main/kotlin/us/wedemy/eggeum/domain/model/notice/NoticeBody.kt
  domain/src/main/kotlin/us/wedemy/eggeum/domain/model/notice/NoticeList.kt
  domain/src/main/kotlin/us/wedemy/eggeum/domain/repository/NoticeRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/domain/usecase/NoticeApi.kt
  domain/src/main/kotlin/us/wedemy/eggeum/domain/util/SuspendCatching.kt
  domain/src/test/kotlin/us/wedemy/eggeum/domain/SuspendCatchingTest.kt
  gradle/libs.versions.toml
  secrets.properties
  settings.gradle.kts
Labels: enhancement, gradle, product

#59 메인화면 import error 해결
  gradle/libs.versions.toml
  main/src/main/AndroidManifest.xml
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MainActivity.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MyAccountFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NewCafeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NoticeAdapter.kt
Labels: bug
