Repository Wedemy/eggeum-android, pull requests merged in 2023-10, with the labels that each got.

#99 정보 수정 요청 화면 추가
  .DS_Store
  app/build.gradle.kts
  data/.DS_Store
  data/src/.DS_Store
  design-resource/.DS_Store
  design-resource/src/.DS_Store
  design-resource/src/main/.DS_Store
  design-resource/src/main/res/.DS_Store
  design-resource/src/main/res/drawable/ic_menu_gray400_24.xml
  design-resource/src/main/res/drawable/ic_trash_20.xml
  settings.gradle.kts
  update-cafe/CODEOWNERS
  update-cafe/build.gradle.kts
  update-cafe/src/main/AndroidManifest.xml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeAddressFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeInfoFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeNameFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeCategoriesFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectInfoCategoriesFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectOpinionFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/UpdateCafeActivity.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/UpdateCafeCompleteFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/UpdateMenuCompleteFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/InputCafeAddressViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/InputCafeInfoViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/InputCafeMenuViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/InputCafeNameViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/SelectCafeCategoriesViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/SelectCafeMenuViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/SelectInfoCategoriesViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/SelectOpinionViewModel.kt
  update-cafe/src/main/res/layout/activity_update_cafe.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_address.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_info.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_menu.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_name.xml
  update-cafe/src/main/res/layout/fragment_select_cafe_categories.xml
  update-cafe/src/main/res/layout/fragment_select_cafe_menu.xml
  update-cafe/src/main/res/layout/fragment_select_info_categories.xml
  update-cafe/src/main/res/layout/fragment_select_opinion.xml
  update-cafe/src/main/res/layout/fragment_update_cafe_complete.xml
  update-cafe/src/main/res/layout/fragment_update_menu_complete.xml
  update-cafe/src/main/res/layout/item_cafe_menu.xml
  update-cafe/src/main/res/layout/item_edit_btn.xml
  update-cafe/src/main/res/navigation/nav_update_cafe.xml
  update-cafe/src/main/res/values/strings.xml
  update-cafe/src/main/res/values/themes.xml
Labels: enhancement, design

#118 페이징 처리 구현
  build-logic/build.gradle.kts
  build-logic/src/main/kotlin/build-logics.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/util/HorizontalSpacingItemDecoration.kt
  design-resource/src/main/res/values/dimens.xml
  gradle/libs.versions.toml
  main/build.gradle.kts
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/res/layout/fragment_home.xml
  main/src/main/res/layout/item_notice_card.xml
Labels: enhancement

#120 clean up
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/us/wedemy/eggeum/android/ui/LoginActivity.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseActivity.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/client/HttpClient.kt
  main/src/main/res/navigation/nav_main.xml
  onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/ui/RegisterAccountFragment.kt
  onboard/src/main/res/navigation/nav_onboard.xml
  register-cafe/src/main/kotlin/us/wedemy/eggeum/android/registercafe/ui/RegisterCafeFragment.kt
  register-cafe/src/main/res/navigation/nav_register_cafe.xml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectInfoCategoriesFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectOpinionFragment.kt
  update-cafe/src/main/res/navigation/nav_update_cafe.xml
Labels: bug

#128 공지 목록 리스트 확장 애니메이션 비활성화
  common/src/main/kotlin/us/wedemy/eggeum/android/common/util/ToggleAnimation.kt
  login/CODEOWNERS
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeListItemViewHolder.kt
  navigator/CODEOWNERS
Labels: bug

#130 구글 로그인 구현 방식 migration
  common/src/main/kotlin/us/wedemy/eggeum/android/common/util/Toolbar.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/util/View.kt
  login/src/main/kotlin/us/wedemy/eggeum/android/login/LoginActivity.kt
Labels: bug

#131 회원 탈퇴 기능 구현
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/WithdrawFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/WithdrawViewModel.kt
Labels: enhancement

#135 공지 리스트 뷰 확장, 축소 애니메이션 관련 이슈 해결
  common/src/main/kotlin/us/wedemy/eggeum/android/common/util/ToggleAnimation.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NoticeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeListItemViewHolder.kt
  main/src/main/res/layout/item_notice_list.xml
Labels: bug, design

#132 로그인 연동 이후에 작업을 위한 merge 요청
  app/src/main/AndroidManifest.xml
  update-cafe/src/main/AndroidManifest.xml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeInfoFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectOpinionFragment.kt
  update-cafe/src/main/res/layout/fragment_input_cafe_info.xml
  update-cafe/src/main/res/navigation/nav_update_cafe.xml
  update-cafe/src/main/res/values/strings.xml
Labels: design
