Repository Wedemy/eggeum-android, pull requests merged in 2024-01, with the labels that each got.

#188 지도 -> 정보수정제안 (인텐트)
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/CafeDetailModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/FileModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/ImageModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/InfoModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/MenuModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/ProductModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeInfoFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/InputCafeInfoViewModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/ProposeCafeInfoViewModel.kt
Labels: bug, enhancement

#189 Authenticator Retry 로직 수정 및 토큰 관리, 에러 처리 보완
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/login/LoginLocalDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/extensions/Exception.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/LoginService.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/TokenAuthenticator.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/util/safeRequest.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/util/Exceptions.kt
  login/src/main/kotlin/us/wedemy/eggeum/android/login/LoginViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/MyAccountFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/MyAccountViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/WithdrawViewModel.kt
Labels: bug, enhancement, refactoring

#191 정보수정제안, 카페 메뉴 수정 시에 다이얼로그 Fragment로 변경
  common/build.gradle.kts
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/CafeDetailModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/FileModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/ImageModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/InfoModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/MenuModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/ProductModel.kt
  gradle/libs.versions.toml
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/FileMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/PlaceMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/FileModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/ImageModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/MenuModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/ProfileImageModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MainActivity.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeImageAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeImageDetailAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeMenuAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeImageViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeMenuViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/MapFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/CafeDetailViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/CafeImageDetailViewModel.kt
  main/src/main/res/navigation/nav_main.xml
  update-cafe/src/main/AndroidManifest.xml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/CafeDetailModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/InfoModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/model/ProductModel.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/DeleteCafeMenuFrament.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeMenuFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/ProposeCafeInfoViewModel.kt
  update-cafe/src/main/res/layout/fragment_delete_cafe_menu.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_address.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_info.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_menu.xml
  update-cafe/src/main/res/layout/fragment_input_cafe_name.xml
  update-cafe/src/main/res/layout/fragment_select_cafe_categories.xml
  update-cafe/src/main/res/layout/fragment_select_cafe_menu.xml
  update-cafe/src/main/res/layout/fragment_select_info_categories.xml
  update-cafe/src/main/res/layout/fragment_select_opinion.xml
  update-cafe/src/main/res/layout/fragment_update_cafe_complete.xml
  update-cafe/src/main/res/layout/fragment_update_menu_complete.xml
  update-cafe/src/main/res/navigation/nav_update_cafe.xml
  update-cafe/src/main/res/values/strings.xml
Labels: refactoring

#193 맵의 위치, 마커와 바텀시트의 카페 정보 동기화
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/CafeDetailModel.kt
  gradle/libs.versions.toml
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/PlaceMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeInfoFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/MapFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/res/layout/fragment_map.xml
  main/src/main/res/layout/fragment_search.xml
Labels: enhancement, design

#195 공지 사항 API 변경된 부분 반영 및 클릭 이벤트 구현
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/CafeDetailModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/model/FileModel.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/util/String.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/notice/NoticeDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/notice/NoticeDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/report/ReportDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/report/ReportDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/mapper/NoticeMapper.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/File.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/file/FileResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/notice/NoticeResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/PlaceResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/place/UpsertPlaceRequest.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/user/User.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/model/user/UserInfoResponse.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/NoticeRepositoryImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/PlaceRepositoryImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/ReportRepositoryImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/NoticeService.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/PlaceService.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/ReportService.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/FileEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/file/FileResponseEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/notice/NoticeEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/place/PlaceEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/place/UpsertPlaceEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/report/UserEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/user/UserInfoEntity.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/NoticeRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/PlaceRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/ReportRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/NoticeUseCase.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/PlaceUseCase.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/ReportUseCase.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/NoticeMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/NoticeCardModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NoticeCardAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/listener/NoticeCardClickListener.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeCardViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/MyAccountFragment.kt
  main/src/main/res/layout/fragment_home.xml
  main/src/main/res/layout/item_notice_card.xml
  main/src/main/res/navigation/nav_main.xml
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/ProposeCafeInfoViewModel.kt
Labels: bug, enhancement, design, refactoring

#199 공지 화면 API 연동 및 공지 검색 기능 구현
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/notice/NoticeDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/paging/NoticePagingSource.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/NoticeUseCase.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/mapper/NoticeMapper.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/NoticeModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/model/NoticeUiModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NoticeAdapter.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeEmptyViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeSearchViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeTitleViewHolder.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/NoticeFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/NoticeItemClickListener.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/HomeViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/NoticeViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchCafeViewModel.kt
  main/src/main/res/layout/fragment_notice.xml
  main/src/main/res/layout/item_notice_empty.xml
  main/src/main/res/layout/item_notice_search.xml
  main/src/main/res/layout/item_notice_title.xml
Labels: enhancement, design

#198 [정보수정제안] ViewModel에서 카페 정보 데이터 관리
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeInfoFragment.kt
  update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/ProposeCafeInfoViewModel.kt
  update-cafe/src/main/res/layout/fragment_input_cafe_info.xml
  update-cafe/src/main/res/values/strings.xml
Labels: refactoring

#203 내 계정 화면 내에 앱 버전 정보 출력
  common/build.gradle.kts
  common/src/main/kotlin/us/wedemy/eggeum/android/common/extension/Activity.kt
  common/src/main/kotlin/us/wedemy/eggeum/android/common/extension/Context.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/MyAccountFragment.kt
  main/src/main/res/layout/fragment_my_account.xml
Labels: enhancement

#205 장소 검색 API distance(반경) 반영
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSourceImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/paging/PlacePagingSource.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/PlaceRepositoryImpl.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/PlaceService.kt
  data/src/main/kotlin/us/wedemy/eggeum/android/data/service/TokenAuthenticator.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/PlaceRepository.kt
  domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/PlaceUseCase.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/CafeDetailViewModel.kt
  main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchViewModel.kt
Labels: bug, enhancement, refactoring

#207 세로 모드 고정
  app/src/main/AndroidManifest.xml
Labels: design

#210 공지 내용 html 태그 핸들링 로직 추가
  main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeListItemViewHolder.kt
  main/src/main/res/layout/item_notice_list.xml
Labels: enhancement, design
